### ISSUE TITLE
Buggy track switching

### ISSUE THREAD

**Issue by jforberg** [jpochyla/psst#251]
**Describe the bug**
I noticed a regression in current master (2961c05a) compared to the version I was previously running (105f6cc2).

When switching tracks, the sound flakes out for a moment. This is the case in both versions, but the behaviour in current master is worse IMO.

In 105f6cc2, there is just a pop artefact.
In 2961c05a, it sounds like if the current track is first paused, then played again for a short time, then the next track starts playing.

Please see attached video samples.

**To Reproduce**
Play one track, then start playing another one.

**Expected behavior**
Clean switch from one track to the next.

**Screenshots**
https://user-images.githubusercontent.com/1269005/148647497-3e551018-efaf-464e-941f-8b33a6b3f67d.mp4
https://user-images.githubusercontent.com/1269005/148647500-7d5d57c0-61f3-4d4c-a8f1-093bbf64c21b.mp4

(The visual artefacts are caused by my screen recorder, not seen in real usage.)

**Environment**
 - OS: Arch Linux
 - Version: 2022-01-07

**Additional context**
Please let me know what additional info would be helpful and I can provide it.

**Comment by jpochyla** [comment]
@jforberg Should be fixed in latest master, can you confirm?

**Comment by jforberg** [comment]
@jpochyla No, the issue is still there in 8f142a3232a706537c8477bff43d2e52309f6b78 unfortunately

**Comment by jacksongoode** [comment]
I can also confirm this behavior on my system.

**Comment by instinctualjealousy** [comment]
This is still the case.

**Comment by arch-btw** [comment]
Ah I thought I was going crazy, I have this issue too. I noticed that it's specifically bad when it's a track that's not cached.

**Comment by Insprill** [comment]
This looks to be caused by `AudioSink#resume`'s StreamMsg to resume arriving before CallbackMsg's PlaySource and Resume messages. This is the order in which things end up being executed:
https://github.com/jpochyla/psst/blob/d70ed8104533dc15bc36b989ba8428872c9b578f/psst-core/src/audio/output/cpal.rs#L118-L120 https://github.com/jpochyla/psst/blob/d70ed8104533dc15bc36b989ba8428872c9b578f/psst-core/src/audio/output/cpal.rs#L127-L130 Start playing audio: https://github.com/jpochyla/psst/blob/d70ed8104533dc15bc36b989ba8428872c9b578f/psst-core/src/audio/output/cpal.rs#L193-L199 Set the audio to be played: https://github.com/jpochyla/psst/blob/d70ed8104533dc15bc36b989ba8428872c9b578f/psst-core/src/audio/output/cpal.rs#L241-L243 https://github.com/jpochyla/psst/blob/d70ed8104533dc15bc36b989ba8428872c9b578f/psst-core/src/audio/output/cpal.rs#L250-L252 Unfortunately, I've looked around a bit and can't see a clear way to fix the issue, but maybe this can point someone in the right direction.

**Comment by wjp** [comment]
I'm also getting this on Linux with cpal's ALSA backend. While debugging this I tried switching cpal to the Jack backend, and that seems to avoid this issue. (Or possibly make it small enough not be noticable.)

Also, looking at the runtime behaviour of the stream callback on my system, the possible explanation given by @Insprill above doesn't seem to be happening here.

That makes me wonder if it could be due to samples remaining in an alsa or hardware buffer, since cpal doesn't seem to let us specify if it should drop any remaining samples in buffers after resuming from the paused state. See https://github.com/RustAudio/cpal/issues/284 .

**Comment by SO9010** [comment]
This is still an issue but for me it's hardly noticeable.

**Comment by oleggtro** [comment]
I'm currently using psst on macOS (built from 2d9bdcb on 2024-07-30 22:50) and can't notice the issue.

**Comment by jacksongoode** [comment]
I don't think its apparent on macOS, but maybe just Linux and Windows?
