### ISSUE TITLE
Can't type credentials

### ISSUE THREAD

**Issue by ShawkMusic** [jpochyla/psst#52]
XFCE Manjaro Linux 5.10.36-2-MANJARO

When I open the program, it shows settings and asks for my credentials. I can click on the buttons and on the text fields but when I try to type, nothing gets written, and whatever I type gets typed on whatever the window was that I had opened before opening psst. 

If I click save and go to the main app and try to type there (eg the search bar), typing works fine, but when i open settings again, it doesnt send the text to it, it only sends it to the main app. This means it's probably a problem with the settings specifically.

This is pretty crucial for me because I can't sign in at all.

**Comment by KaMiila** [comment]
I am having the same issue on Artix (open-rc port of Arch linux).

**Comment by jpochyla** [comment]
Seems like an issue in Linux Druid key handling.

**Comment by KaMiila** [comment]
if i could figure out the syntax for username and password in the config.json file I could just input it manually in there.  but I have no idea what it should look like.

{
  "credentials": null,
  "audio_quality": "High",
  "theme": "Dark"
}

**Comment by jpochyla** [comment]
The credentials field contains a token retrieved from Spotify, it's unfortunately not possible to put username & password there.

Tangential: Psst really needs somebody to take care of Linux and Windows platforms, I've created #54 for this.

**Comment by KaMiila** [comment]
What generates or pulls in that token?  If I can figure out what my token is I can just input it directly to the config.json file

**Comment by Liberatys** [comment]
@jpochyla @KaMiila I'm looking into the issue with username/password entry on linux

**Comment by jpochyla** [comment]
@Liberatys I've pushed an update that uses the latest Druid master. If it doesn't help, let's report the issue upstream.

**Comment by Liberatys** [comment]
@jpochyla The changes in dependencies did not resolve the issue 🤔 I found a way to make the inputs work on Linux and also show the window on the proper screen if you are using multiple screens. https://github.com/jpochyla/psst/pull/55. I don't know in what way that influences the appearance on macOS.

**Comment by freidrichen** [comment]
I was able to work around the problem by entering my username/password in the config like this:

```
"credentials": {
  "username": "my-username",
  "auth_data": "my-password",
  "auth_type": 0
}
```

**Comment by jpochyla** [comment]
> I don't know in what way that influences the appearance on macOS.

Only in very minor way, let's keep it like this.

> I was able to work around the problem by entering my username/password in the config like this:

Oh, great idea! I totally forgot the type is an enum.

So I'm considering the issue solved by #55, closing. Thank you everbody!

**Comment by Hexality** [comment]
what about facebook login?

**Comment by andykais** [comment]
@Hexality I just found out that if you are logged in w/ a first party auth (e.g. facebook or google), you can still setup a device password. Go to your spotify account and click the tab "Set device password" or just click this link https://www.spotify.com/us/account/set-device-password/. 

@jpochyla it might be worth adding this to the readme for users that didnt sign up w/ a username & password.
