### ISSUE TITLE
No function `new_with_name` for struct `MediaControls`

### ISSUE THREAD

**Issue by olligobber** [jpochyla/psst#64]
When installing from the aur (https://aur.archlinux.org/packages/psst-git/) I got the following error:

```
   Compiling psst-gui v0.1.0 (/home/oliver/.cache/yay/psst-git/src/psst/psst-gui)
error[E0599]: no function or associated item named `new_with_name` found for struct `MediaControls` in the current scope
  --> psst-gui/src/controller/playback.rs:87:49
   |
87 |         let mut media_controls = MediaControls::new_with_name("psst", "Psst");
   |                                                 ^^^^^^^^^^^^^ function or associated item not found in `MediaControls`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `psst-gui`

To learn more, run the command again with --verbose.
==> ERROR: A failure occurred in build().
    Aborting...
error making: psst-git
```

**Comment by Anuj2976** [comment]
+1

**Comment by jpochyla** [comment]
I'm sorry for the broken build, it should be fixed in master now.

**Comment by graynk** [comment]
When I build from master on Linux I still get this:
```Bash
error[E0599]: no function or associated item named `new_with_name` found for struct `MediaControls` in the current scope
  --> psst-gui/src/controller/playback.rs:87:49
   |
87 |         let mut media_controls = MediaControls::new_with_name("psst", "Psst");
   |                                                 ^^^^^^^^^^^^^ function or associated item not found in `MediaControls`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `psst-gui`
```

Seems like MediaControls now has only `new()` constructorm which accepts `PlatformConfig`

I hacked this together and it compiled:
```Rust
#[cfg(not(target_os = "windows"))]
let hwnd = None;
#[cfg(target_os = "windows")]
let hwnd = {
    use raw_window_handle::windows::WindowsHandle;

    let handle: WindowsHandle = unimplemented!();
    Some(handle.hwnd)
};
let config = PlatformConfig {
    dbus_name: "psst",
    display_name: "Psst",
    hwnd,
};
let mut media_controls = MediaControls::new(config).unwrap();
```

Media Controls via gnome extensions / media keys seem to work as well

**Comment by etcet** [comment]
I had this same problem but it was because I had run `cargo update` in the repo. From a clean repo it built fine.

**Comment by graynk** [comment]
> I had this same problem but it was because I had run `cargo update` in the repo. From a clean repo it built fine.

I looked at the bash history and I indeed I did, sorry for the bother

**Comment by jpochyla** [comment]
Fixed in latest master.
